Added sample data and implemented load on startup
KantwonsKids/DonationTracker pull request #30
Opened 2018-10-10 20:09 UTC by ewilson72

Can someone test this?  I can't run the emulator on my laptop.  It should print to terminal either success or an exception message

2018-10-10 22:06 UTC, danielprofili commented on app/src/main/res/raw/SampleData.csv
> +﻿Key,Name,Latitude,Longitude,Street Address,City,State,Zip,Type,Phone,Website
I get an error on build that says res/raw files can't be uppercase but renaming to `sampledata.csv` worked

2018-10-10 22:13 UTC, danielprofili requested changes
After changing two things I got a success message and after debugging to see the donation data list it appears to have worked!

2018-10-10 22:13 UTC, danielprofili commented on app/src/main/res/raw/SampleData.csv
> +﻿Key,Name,Latitude,Longitude,Street Address,City,State,Zip,Type,Phone,Website
res/raw files can't have uppercase apparently (it wouldn't build) but renaming to `sampledata.csv` worked for me

2018-10-10 22:13 UTC, danielprofili commented on app/src/main/java/kantwonskids/donationtrackerg14b/controller/WelcomeActivity.java
> +            System.out.print("Successfully populated the donationDataList");
I don't think you can println() in android, you have to do `Log.d()` I think

2018-10-11 17:33 UTC, AidanMulaokar submitted a review, later dismissed

2018-10-11 18:19 UTC, aschmitt8 reviewed
looks good! got it to work after making the two changes daniel mentioned (changing system.out.println to log.d and changing the name of SampleData.csv to sampledata.csv). so i'll approve once those changes are made

2018-10-12 00:03 UTC, ewilson72 commented
fixed the stuff

2018-10-12 02:52 UTC, AidanMulaokar submitted a review, later dismissed

2018-10-12 17:33 UTC, aschmitt8 approved these changes

2018-10-13 03:56 UTC, danielprofili approved these changes

2018-10-13 15:34 UTC, AidanMulaokar approved these changes

2018-10-13 18:16 UTC, merged