Items
KantwonsKids/DonationTracker pull request #43
Opened 2018-10-17 19:42 UTC by jpetrillo3

2018-10-17 21:26 UTC, danielprofili requested changes

2018-10-17 21:26 UTC, danielprofili commented on app/src/main/java/kantwonskids/donationtrackerg14b/model/Location.java
> +    private List<Donation> donations;
minor thing but it might be better for this to be a Collection, because it doesn't really have to be a list. if it's a collection it can be literally anything (hashset, linkedlist, etc)

2018-10-17 21:26 UTC, danielprofili commented on app/src/main/java/kantwonskids/donationtrackerg14b/model/Location.java
>       * Constructor that takes in type-appropriate data
javadoxxxxxxxxxxxxxxxxxxx

2018-10-17 21:26 UTC, danielprofili commented on app/src/main/java/kantwonskids/donationtrackerg14b/model/Location.java
> +    public void setDonations(List<Donation> donations) {
javadoxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

2018-10-17 21:35 UTC, danielprofili requested changes

2018-10-17 21:35 UTC, danielprofili commented on app/src/main/java/kantwonskids/donationtrackerg14b/model/Donation.java
> +    public String getItem() {
I feel like "getName" would make more sense

2018-10-17 22:13 UTC, aschmitt8 commented on app/src/main/java/kantwonskids/donationtrackerg14b/model/Location.java
>       * Constructor that takes in type-appropriate data
none of the getters and setters in Location have javadocs either, do we need all of them too? or just the addDonation methods that aren't getters and setters?

2018-10-17 22:22 UTC, danielprofili commented on app/src/main/java/kantwonskids/donationtrackerg14b/model/Location.java
>       * Constructor that takes in type-appropriate data
technically everything that is public should have javadocs so yes

2018-10-17 22:51 UTC, aschmitt8 submitted a review, later dismissed
I agree with Daniel's suggestions for changes, but other than that looks great!

2018-10-17 22:53 UTC, AidanMulaokar approved these changes

2018-10-18 14:06 UTC, ewilson72 reviewed
I agree with Daniel's change from item to name

2018-10-18 14:27 UTC, jpetrillo3 commented on app/src/main/java/kantwonskids/donationtrackerg14b/model/Location.java
>       * Constructor that takes in type-appropriate data
That wasn't me lol that was Ethan but I can add them

2018-10-18 14:27 UTC, jpetrillo3 commented on app/src/main/java/kantwonskids/donationtrackerg14b/model/Location.java
> +    public void setDonations(List<Donation> donations) {
Oh lol these were me

2018-10-18 19:43 UTC, AidanMulaokar submitted a review, later dismissed

2018-10-19 00:28 UTC, jpetrillo3 commented
I just thought that it wasn't really the name of the donation, it was the name of the item. I'll change it though

2018-10-19 01:55 UTC, danielprofili approved these changes

2018-10-19 02:10 UTC, ewilson72 approved these changes

2018-10-19 13:14 UTC, AidanMulaokar approved these changes

2018-10-19 13:15 UTC, merged