Lockout after 3 incorrect login attempts
KantwonsKids/DonationTracker pull request #91
Opened 2018-11-24 16:29 UTC by aschmitt8

the dialog just basically blocks the user from doing anything for five minutes after you try to log in incorrectly 3 times. to test this, you don't actually have to wait 5 minutes, just change the number of milliseconds to like 5000 on line 94 of LoginActivity

2018-11-24 22:39 UTC, danielprofili requested changes
Maybe look into making dialog boxes non-dismissable? Also, once we annihilate the welcome activity #70, we won't be able to go back to it. So maybe instead of going back there just reset the counter to zero and clear the username/password field or something.

Other than that it looks good

2018-11-24 22:39 UTC, danielprofili commented on app/src/main/java/kantwonskids/donationtrackerg14b/controller/LoginActivity.java
> +    private static int LOCKOUT_NUMBER = 2;
should be final probably

2018-11-24 22:39 UTC, danielprofili commented on app/src/main/java/kantwonskids/donationtrackerg14b/controller/LoginActivity.java
> +            }, 10000);
also should use named constant here instead of magic number

2018-11-25 23:01 UTC, aschmitt8 commented
Alright I fixed all of the magic numbers, the dialog box is now not-dismissable (lol I thought I had already done that but now you actually can't just click out of it, I checked). Also, now the username and password field will just be reset after the delay as opposed to going back to the welcome screen.

2018-11-27 02:46 UTC, danielprofili submitted a review, later dismissed

2018-11-29 14:55 UTC, WahahaYes submitted a review, later dismissed

2018-12-01 15:42 UTC, jpetrillo3 commented
Something is wrong. I registered and logged in to make sure none of that was affected, but then I logged out and typed random nonsense for my password and still got into the app. not sure why

2018-12-01 15:44 UTC, jpetrillo3 commented
If I type a random username and password, I don't get in; but if I type a registered username and nonsense for a password, I get in

2018-12-03 01:43 UTC, jpetrillo3 approved these changes

2018-12-03 03:38 UTC, AidanMulaokar approved these changes

2018-12-03 21:52 UTC, danielprofili approved these changes

2018-12-03 22:20 UTC, merged